// Global using directives

global using AutoMapper;
global using QuickStart.Api.Controllers;
global using QuickStart.Api.Middlewares;
global using QuickStart.Domain.DTOs;
global using QuickStart.Domain.Exceptions;
global using QuickStart.Service.Interfaces;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using Moq;
global using System;
global using System.Collections.Generic;
global using System.Net;
global using System.Security.Claims;
global using System.Text.Encodings.Web;
global using System.Threading.Tasks;
global using QuickStart.Api.Mappings;
global using QuickStart.Api.Security.Authentication;
global using QuickStart.Api.Security.Authorization;
global using QuickStart.Domain.Configurations;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Primitives;
global using Microsoft.Net.Http.Headers;
global using Xunit;
